import Head from 'next/head'
import { Inter } from '@next/font/google'
import Footer from '@/component/Footer'
import Header from '@/component/Header'
import Main from '@/component/Main'
import Learner from '@/component/Learner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Main />
        <Learner />
        <Footer />
      </div>
    </>
  )
}
