<<<<<<< HEAD
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Footer from "@/component/Footer";
import Header from "@/component/Header";
import Main from "@/component/Main"
import Learner from "@/component/Learner"
=======
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/component/Footer'
>>>>>>> 57376f2 (feat:Add footer component)

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD
      <div>
        <Header />
        <Main />
        <Learner />
      </div>
    </>
  );
}
=======
      <main>
        <Footer/>
        {/* <h1 className={tab}>Hello world!</h1> */}
      </main>
    </>
  )
}

// const tab = 'text-3xl font-bold underline text-red text-50'
>>>>>>> 57376f2 (feat:Add footer component)
